name: first
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
jobs:
  job1:
    name: FirstJob
    runs-on: ubuntu-latest
    steps:
    - name: get-date
      run: date
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: env | sort

  job2:
    name: SecondJob
    runs-on: windows-latest
    steps:
    - name: get-date
      run: date
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: "Get-ChildItem Env: | Sort-Object Name"

  job3:
    name: ThirdJob
    runs-on: windows-latest
    needs: [job1, job2]
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: "Get-ChildItem Env: | Sort-Object Name"
    - name: Markdown Linting Action
      # You may pin to the exact commit or the version.
      # uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb
      uses: avto-dev/markdown-lint@v1.5.0
      with:
        # Custom rule files (file|directory|glob|package)
        rules: # optional
        # Configuration file (JSON, JSONC, or YAML)
        config: # optional
        # Fix basic errors
        fix: # optional, default is false
        # Write issues to file
        output: # optional
        # Files to ignore/exclude
        ignore: # optional
        # Files (directories|globs) for a work or any additional arguments
        args: 
